models:
  - "Salesforce/codegen-350M-mono"
  - "Salesforce/codegen-2B-mono":
      device: "gpu"
  - "Salesforce/codegen-6B-mono":
      device: "gpu"
      precision: "float16"
history:
  - "# Import libraries."
  - "import numpy as np"
prompts:
  - "Assign the string \"abcde\" to a variable named \"my_string\"."
  - "Lowercase the given string \"my_string\"."
  - "Assign the distinct characters of the string to a variable named \"chars\"."
  - "Sort these characters in alphabetical order."
  - "Print the resulting list of characters."
general_device: "cpu"
general_precision: "float32"
debug: True
